Remark plugin for parsing tags in Markdown
vnLab-Lodz/vnLab-series-template pull request #10
Opened 2022-12-05 02:08 UTC by LostInStatic

This plugin will find all the tags found in the markdown files (following`(displayed text|keyword):{{#tag name}}` syntax), and create corresponding nodes in the data layer. If `|keyword` is ommited, the display text will be used as a keyword.

It will not clean up stale data on multiple runs, so expect some pollution when hot-rebuilding pages.

`gatsby-plugin-mdx` version was bumped up to allow proper processing of the plugin's `gatsby-node.js`.

2022-12-05 18:02 UTC, karczewskiPiotr requested changes
Seems like the plugin matches some unwanted strings if there are more than one `()`

![image](https://user-images.githubusercontent.com/34404855/205652112-d18df069-bbd5-46b5-ae67-e55cecf911d8.png)

The current one additionally seems to catch empty `{{#}}`.

---

This is what I managed to come up with → `((\([^\(\)]*\))|(\({2}[^\(\)]*\){2})):{{#([\w\s]+)}}`.

![image](https://user-images.githubusercontent.com/34404855/205709136-c75677c1-685f-4f91-b3a3-387d0768d30b.png)

You can check if it is compatible with all options if I missed any.

--- 

I also need to modify the footnotes plugin a bit more to make sure the footnotes catch 100% of wrapped tags but I'll push that today to Model i metafora and perhaps add the plugin to this repo as well.

2022-12-05 18:02 UTC, karczewskiPiotr commented on plugins/remark-tags-plugin/index.js
> +}
@LostInStatic I'm finding this a bit hard to read and looks like a lot of spreading and extraction of stuff from prexisting nodes and arrays.

Had a refactoring hunch to scratch so I came up with this for a more readable flow (perhaps? let me know). Turned `tags` into a map and used `insertTags` instead of `tags.push`. Use of maps might provide a tiny performance boost. It could also be improved by passing `markdownNode.id` to `insertTag` function in order to get rid anchor mapping. We could switch to this approach if we deem it viable. Let me know what you think.

However, there is one thing that we need to do no matter the code readability. We need to use `Promise.all` for executing `actions.createNote` as for 3 tags only it decreases the time from 500ms to 300ms so I presume it will save us loads of build time given the amount of tags that will be put in.

```js
const createNodesFromAnchors = async (tags, util) => {
  const mdx = util.markdownNode.id
  const promises = []

  for (const [category, keywords] of tags) {
    const tag = { category, keywords: [] }

    for (const [keyword, anchors] of keywords) {
      tag.keywords.push({
        keyword,
        anchors: anchors.map(id => ({ id, mdx })),
      })
    }

    const contentDigest = util.createContentDigest(tag)
    tag.id = util.createNodeId(`TAGS__${category}`)
    tag.internal = { type: "Tags", contentDigest }
    promises.push(util.actions.createNode(tag))
  }

  await Promise.all(promises)
}

const insertTag = (tags, { keyword, category, anchorId: anchor }) => {
  const keywords = tags.get(category)
  if (!keywords) {
    tags.set(category, new Map([[keyword, [anchor]]]))
    return
  }

  const anchors = keywords.get(keyword)
  if (!anchors) {
    keywords.set(keyword, [anchor])
    return
  }

  anchors.push(anchor)
}
```

2022-12-05 18:02 UTC, karczewskiPiotr commented on plugins/remark-tags-plugin/index.js
> +    return u("jsx", extractData(match, regexp, tags))
Use of only one jsx node is probably fine as we would usually aim for tags to be last in the execution of plugins. If we would like to be safe we could instead split it into couple children and leave he `displayText` as a text node like in the case of footnotes plugin.

![image](https://user-images.githubusercontent.com/34404855/205695481-e0bcc74d-a2b4-4cf4-9f9f-a1e28882e149.png)

2022-12-05 18:09 UTC, karczewskiPiotr commented
@LostInStatic I added the support to Model i metafora but not here since this is a forked repo branch. However, tested it locally and worked all good so should be fine in the future.

![image](https://user-images.githubusercontent.com/34404855/205710427-05fcc784-6cb1-4125-b327-5ddd23680765.png)

2022-12-11 21:46 UTC, LostInStatic commented on plugins/remark-tags-plugin/index.js
> +}
Put together a solution that incorporates your approach - not sure if it is more readable in the end, but should be more performant at least 🤞

2022-12-12 14:28 UTC, karczewskiPiotr approved these changes

2022-12-12 14:28 UTC, merged